events {}

http {
  server {
    listen 80;
    server_name _;

    root /etc/proxy-orchestrator/runtime/decoy-site;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
